name: Docker image Build Process

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  docker:
    env:
     appName: "springboot-image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven

      - name: Check Docker Hub Username
        env:
          USER_DOCKER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          if [ -z "$USER_DOCKER" ]; then
            echo "Docker Hub Username is not set"
            exit 1
          else
            echo "Docker Hub Username is set"
          fi
