name: Docker image Build Process

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check Docker Hub Username
      env:
        USER_DOCKER: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        if [ -z "$USER_DOCKER" ]; then
          echo "Docker Hub Username is not set"
          exit 1
        else
          echo "Docker Hub Username is set"
        fi      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

