name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Docker Hub Username
      env:
        USER_DOCKER: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        if [ -z "$USER_DOCKER" ]; then
          echo "Docker Hub Username is not set"
          exit 1
        else
          echo "Docker Hub Username is set"
        fi
